#!/usr/bin/env python3
"""Mirror .agents/skills (canonical, read by Codex) into .claude/skills (read by Claude Code).

Usage:
    python scripts/sync_skills.py --write   # regenerate the mirror
    python scripts/sync_skills.py --check   # exit 1 if the mirror differs (used in CI)

The mirror copies every file of every skill directory, adds a GENERATED marker file, and fails --check on
missing, extra or modified files.
"""
from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / ".agents" / "skills"
DST = ROOT / ".claude" / "skills"
MARKER = "GENERATED-FROM-.agents-skills.txt"
MARKER_TEXT = "Generated by scripts/sync_skills.py from .agents/skills. Do not edit here.\n"


def file_map(base: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not base.exists():
        return out
    for p in sorted(base.rglob("*")):
        if p.is_file():
            rel = p.relative_to(base).as_posix()
            if rel == MARKER:
                continue
            out[rel] = hashlib.sha256(p.read_bytes()).hexdigest()
    return out


def write() -> None:
    if DST.exists():
        shutil.rmtree(DST)
    shutil.copytree(SRC, DST)
    (DST / MARKER).write_text(MARKER_TEXT, encoding="utf-8")
    print(f"mirrored {len(file_map(SRC))} files to {DST}")


def check() -> int:
    src, dst = file_map(SRC), file_map(DST)
    problems = []
    for rel in sorted(set(src) | set(dst)):
        if rel not in dst:
            problems.append(f"missing in mirror: {rel}")
        elif rel not in src:
            problems.append(f"extra in mirror: {rel}")
        elif src[rel] != dst[rel]:
            problems.append(f"differs: {rel}")
    if not (DST / MARKER).exists():
        problems.append("marker file missing in mirror")
    for p in problems:
        print(p)
    if problems:
        print("run: python scripts/sync_skills.py --write")
        return 1
    print(f"skills mirror in sync ({len(src)} files)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    args = ap.parse_args()
    if args.write:
        write()
        return 0
    return check()


if __name__ == "__main__":
    sys.exit(main())
